var initSettings = {
  sampling : 1,
  font : "Roboto Mono Regular",
  fontPaths: {"Brandon Grotesque Regular":"BrandonGrotesque-Regular.ttf",
          "Roboto Black":"Roboto-Black.ttf",
          "Roboto Black Italic":"Roboto-BlackItalic.ttf",
          "Roboto Bold" : "Roboto-Bold.ttf",
          "VT323 Regular" : "VT323-Regular.ttf",
          "Akzidenz Grotesk Next Black" : "Akzidenz Grotesk Next Black.otf",
          "Akzidenz Grotesk Next Regular" : "Akzidenz Grotesk Next Regular.otf",
          "Arial Regular" : "arial.ttf",
          "Courier New" : "Courier New.ttf",
          "DIN Light" : "DIN-Light.otf",
          "DIN Medium" : "DIN-Medium.otf",
          "Nunito Regular" : "Nunito-Regular.ttf",
          "Portrait Text Web Bold" : "PortraitTextWeb-Bold.otf",
          "Portrait Text Web Medium" : "PortraitTextWeb-Medium.otf",
          "Proxima Nova Bold" : "ProximaNova-Bold.otf",
          "Proxima Nova Regular" : "ProximaNova-Regular.otf",
          "Sentinel Bold" : "Sentinel Bold.otf",
          "Shrikhand Regular" : "Shrikhand-Regular.ttf",
          "Source Code Regular" : "SourceCodePro-Regular.ttf",
          "Roboto Mono Regular" : "RobotoMono-Regular.ttf",
          "Taz Bold" : "TazBold.otf"},
  fontsLoaded : {},
  currentFont : undefined,
  sampleFactor : 0.08,
  simplifyThreshold : 0,
  fontSize : 200,
  color : [0,0,0],
  strokeColor : [0,0,0],
  backgroundColor : [255,255,255],
  xStart : window.innerWidth*0.05,
  yStart : window.innerHeight*0.23,
  stroke : true,
  shapeSize : 4,
  shapeXSize : 4,
  shapeYSize : 4,
  strokeWeight : 1,
  xSpace : 5,
  ySpace : 5,
  rotate : 0,
}
var SETTINGS = initSettings;
